gRPC adjustments
murano-app/murano-order-processing pull request #46
Opened 2023-07-18 14:12 UTC by alexandrter

-notify other waiters about tableSessionUuid rewriting
-notify waiter about current orders when subscribing to a table
-fix bug with order meals removal on accepting order
-get rid of nested orders property
-add validation when placing order on closed table session
-disallow callWaiter/askBill/getOrderMeals for expired sessions

2023-07-18 14:17 UTC, alexandrter commented on src/main/java/com/murano/service/OrderProcessingServiceImp.java
>          TableSessionEntity tableSessionEntity = tableSessionRepository.findByUuid(tableSessionUuid)
.findByUuidAndClosedAtIsNull

2023-07-19 10:24 UTC, donesvad requested changes
fix comment

2023-08-06 18:33 UTC, alexandrter commented on src/main/java/com/murano/service/OrderProcessingServiceImp.java
>          TableSessionEntity tableSessionEntity = tableSessionRepository.findByUuid(tableSessionUuid)
fixed

2023-08-06 18:37 UTC, alexandrter commented on src/main/java/com/murano/service/OrderProcessingServiceImp.java
> -                    .setOrderMeals(expectedOrderMealList);
orderMeals are optional in request. if we just ACCEPT we do not have to transmit order meals. In that case the .setOrderMeals has been setting orderMeals to emty list which for hibernate meant "remove all order meals"

2023-08-07 12:32 UTC, donesvad commented on src/main/java/com/murano/api/TableController.java
> +    //todo discuss what the purpose of this endpoint is. why don't we return OrderMeals as a response for askBill?
because we need to show ordered products before the bill is asked

2023-08-07 12:33 UTC, donesvad commented on src/main/java/com/murano/api/exception/BusinessErrorResponse.java
> +    TABLE_SESSION_CLOSED(HttpStatus.NOT_FOUND, 121, Code.NOT_FOUND, "Table session %s has been closed"),
Don't see any usage

2023-08-07 12:45 UTC, donesvad commented on src/main/java/com/murano/api/TableController.java
revert please

2023-08-07 12:46 UTC, donesvad commented on src/main/java/com/murano/grpc/service/TableGrpcServiceImpl.java
> +        //notify about all previous notifications of the table session in question
could you explain it please?

2023-08-07 14:49 UTC, alexandrter commented on src/main/java/com/murano/api/TableController.java
todo was removed and the imports are now on the right place

2023-08-07 15:13 UTC, donesvad approved these changes

2023-08-08 10:28 UTC, merged