MUR-387 add romanian translations
murano-app/murano-order-processing pull request #74
Opened 2024-03-17 13:27 UTC by alexandrter

2024-03-17 15:08 UTC, donesvad commented on src/main/resources/messages_ro.properties
> +notification.another-device-login.title=Login nou!
Chat GPT reply:

- notification.waiter-interaction.acknowledged={0} în drum - This message is concise. However, to make it more natural, you might consider "{0} se îndreaptă către masă" if the context is that the person is heading towards the table.
- notification.waiter-interaction.pay.card=Clientul vrea sa achite cu card - The message is clear, but there's a minor typo: it should be "să achite" with a diacritical mark on "ă".
- notification.waiter-interaction.pay.cash=Clientul vrea să achite cu numerar - Also clear, with the correction applied for "să".
- notification.session-closed={0} a închis sessuinea - There's a typo here; it should be "sesiunea", not "sessuinea".
- notification.another-device-login.body=Ați intrat în aplicație de pe alt dispozitiv. Reconectați-vă de pe acest dispozitiv pentru a continua să primiți notificări. - This message is clear and instructive, though "Ați intrat în aplicație de pe un alt dispozitiv." might flow slightly better for readability.

2024-03-17 15:08 UTC, donesvad requested changes
fix comment

2024-03-18 20:18 UTC, alexandrter commented on src/main/resources/messages_ro.properties
> +notification.another-device-login.title=Login nou!
1-4 fixed. didn't change the 5 because in other languages we inform the waiter what to do to continue receiving notifications. I see no reason to cut half of the information out just in Romanian just because GPT said so.

Please fix "в пути" for Russian translation as well, since we decided to go with the long form. Btw. " se îndreaptă către masă" is a nonsence, I talked with Misha and Dima and they came up with " vine spre masa"

2024-03-19 01:52 UTC, donesvad approved these changes

2024-03-19 13:35 UTC, merged